### ISSUE TITLE
Does not format header properly when replying from a message window

### ISSUE THREAD

**Issue by pkimpel** [caligraf/ChangeQuote#10]
ChangeQuote 1.2 seems to work properly for me on Thunderbird 68.4.1 (32-bit) when replying to a message selected from the Inbox. When selecting reply (or Ctrl-R) from a message opened in a separate window, however, I get one of two strange behaviors:

1. The simple, default, one-line header is formatted.
2. The multi-line ChangeQuote header is formatted, but for the message currently highlighted in the Inbox, not the message being replied to.

**Comment by caligraf** [comment]
Hello,
There was a bug that I have fixed in version 1.3 : if the message is opened in a new window the reply header is incorrect or the original one.
Can you try with version 1.3 or 1.4 ?

**Comment by pkimpel** [comment]
I updated to 1.4 on 1 February (or T-Bird updated it automatically, I can't remember which), and it's been working fine ever since then. I had originally installed 1.2 from the Add-ons site in mid-January. Thanks for developing this add-on -- I like the way it works.
