### ISSUE TITLE
"%A" becomes "AM" for times around noon

### ISSUE THREAD

**Issue by ObjectBoxPC** [caligraf/ChangeQuote#12]
The "%A" and "%a" strings become "AM" and "am" respectively for times around noon. For example, 12:30 (24-hour clock) with the format string "%h:%i %A" becomes "12:30 AM".

In the United States, the usual convention is that times from 00:00 to 00:59 (24-hour clock) are 12:00 AM to 12:59 AM, and times from 12:00 to 12:59 (24-hour clock) are 12:00 PM to 12:59 PM. I don't know if this is the more common convention worldwide.

**Comment by caligraf** [comment]
I have fixed it in 1.5.1 version [https://github.com/caligraf/ChangeQuote/releases/tag/1.5.1](https://github.com/caligraf/ChangeQuote/releases/tag/1.5.1)

**Comment by caligraf** [comment]
I close the issue, version 1.5.1 is available at [https://addons.thunderbird.net/fr/thunderbird/addon/changequote/](https://addons.thunderbird.net/fr/thunderbird/addon/changequote/ )
