### ISSUE TITLE
"%h" becomes "0" for times around midnight

### ISSUE THREAD

**Issue by ObjectBoxPC** [caligraf/ChangeQuote#13]
The "%h" string becomes "0" for times around midnight For example, 00:30 (24-hour clock) with the format string "%h:%i %A" becomes "0:30 AM" instead of "12:30 AM".

**Comment by caligraf** [comment]
I have fixed it in 1.5.1 version [https://github.com/caligraf/ChangeQuote/releases/tag/1.5.1](https://github.com/caligraf/ChangeQuote/releases/tag/1.5.1)

**Comment by caligraf** [comment]
I close the issue, version 1.5.1 is available at [https://addons.thunderbird.net/fr/thunderbird/addon/changequote/](https://addons.thunderbird.net/fr/thunderbird/addon/changequote/ )
