### ISSUE TITLE
what is the format to generate line breaks in plain text customized reply headers? 

### ISSUE THREAD

**Issue by gessel** [caligraf/ChangeQuote#15]
From the configuration screen shots, one would (as expcted) use <br> to insert line breaks for HTML formatted reply messages.  This doesn't seem to convert to line breaks in plain text formatted replies whether "add a linebreak in text plain headers" is selected or not.  But maybe I'm missing an obvious permutation.

\n or ^M or \r\n would be sort of texty-but I'd think it would break HTML replies and if "Use in reply the same format (html or text) is selected, it would seem desirable that a single customized reply header would be interpreted for both text and HTML, at least translating <br> to \r\n - Chr(13)Chr(10) for text-only mail (and omitting other HTML tags).

**Comment by caligraf** [comment]
in version 1.5.1 [https://github.com/caligraf/ChangeQuote/releases/tag/1.5.1](https://github.com/caligraf/ChangeQuote/releases/tag/1.5.1) you can have a multiples lines customized header,  In the options window of ChangeQuote I replaced one line field by a multiple lines text field.

**Comment by caligraf** [comment]
closing because multiple lines text field should solve your issue.
