### ISSUE TITLE
Does not work anymore with TB 78.3.2

### ISSUE THREAD

**Issue by balvie** [caligraf/ChangeQuote#16]
I use TB 78.3.2 (32-bit) and when trying to install it on another laptop, TB that this nice extension is not compatible.

**Comment by caligraf** [comment]
I'm working on a new version compatible with Thunderbird 78.

**Comment by balvie** [comment]
Great, if there is anything I can do to help your, e.g. testing, pls let me know.

**Comment by caligraf** [comment]
I prefer to keep open this issue until version compatible with 78 is available.

**Comment by caligraf** [comment]
I have created a version 1.5 compatible with TB 78 [https://github.com/caligraf/ChangeQuote/releases/tag/1.5](https://github.com/caligraf/ChangeQuote/releases/tag/1.5)
