### ISSUE TITLE
"Close message window after forward" option request.

### ISSUE THREAD

**Issue by Duncan-Moore** [caligraf/ChangeQuote#17]
I use this add-on for the "Close message window after reply" option.

When it's TB78 compatible, would it be possible to also have a "Close message window after _forward_" option?
Or maybe it could just be a combined "Close message window after _reply/forward_" option?

**Comment by caligraf** [comment]
I added the combined "Close message window after reply/forward" option in version 1.5.1 [https://github.com/caligraf/ChangeQuote/releases/tag/1.5.1](https://github.com/caligraf/ChangeQuote/releases/tag/1.5.1)

**Comment by Duncan-Moore** [comment]
Yes, that's working. Many thanks.
