### ISSUE TITLE
Customised date format not working

### ISSUE THREAD

**Issue by Lemoert** [caligraf/ChangeQuote#22]
Just installed ChangeQuote on a new computer and for some reason only options starting with "%%" work while customised date formats with "%" do not. See attached examples. I tried both with the options alone and in various parentheses, as well as the different "Use long or customized format in date field" options without any luck,

(ChangeQuote 1.5.1, Thunderbird 78.6.0, Fedora 33)

Let me know if you need any other information or if I am missing something!

Thanks,
Martin

![Screenshot_2021-01-20_13-42-37](https://user-images.githubusercontent.com/44477593/105177392-e7c0f700-5b26-11eb-9b6f-cdfa78197f16.png)
![Screenshot_2021-01-20_13-42-58](https://user-images.githubusercontent.com/44477593/105177400-e98aba80-5b26-11eb-9eac-d5bd25ce5f6e.png)

**Comment by Theowoll** [comment]
Use %%5 for the date. Use the date format specifiers (with single '%') in the "Customized format" input fields of the dialog.

**Comment by Lemoert** [comment]
Thanks @Theowoll! Works fine now :)
