### ISSUE TITLE
Didn't see option buttion for ChangeQuote in 78.9.0

### ISSUE THREAD

**Issue by banshann** [caligraf/ChangeQuote#27]
![image](https://user-images.githubusercontent.com/48432781/113269343-eff99780-930a-11eb-8293-8ac64570675b.png)

Does anyone know how to configure ChangeQuote in 78.9.0? Thanks!

**Comment by gtback** [comment]
For me, on macOS, it's under **Tools** -> **Add-on Options** -> **changeQuote**

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1045796/118161105-cdb46880-b3e4-11eb-86c3-612ee7c327f5.png">

**Comment by damjang** [comment]
No Add-on Options -> Changequote in TB 78.14.0 win7

**Comment by caligraf** [comment]
For information it is explained in FAQ of Thunderbird:
https://support.mozilla.org/en-US/kb/thunderbird-add-ons-frequently-asked-questions
https://support.mozilla.org/en-US/kb/thunderbird-add-ons-frequently-asked-questions#w_how-do-i-configure-add-ons
