### ISSUE TITLE
TB 91.0 Support

### ISSUE THREAD

**Issue by BillH99999** [caligraf/ChangeQuote#28]
There doesn't appear to be any way to change ChangeQuote's options in TB 91.0.  Tools > Add-on preferences doesn't exist any longer.

Am I missing something?

Thanks,
Bill

**Comment by bhotrock** [comment]
I'm encountering the same issue.  When clicking the ... menu for the extension (on the "Enabled" page) there is an option for "Manage".  However, selecting that option shows the same page as just clicking on the extension:  The details and permissions page.  I can't locate the actual multi-tabbed "Change Quote and Reply Format" window which used to be accessed through:  Tools - Add-on Options - changeQuote.  I'm assuming this has to do with the removal of the Tools - Add-on Options menu item in TB 91.

**Comment by amourchaleur** [comment]
Same issue here. Mark message as read when replied also does not work in TB 91.

**Comment by Stonewall6165** [comment]
Same issue. It would be nice if you can fix it.

**Comment by BillH99999** [comment]
I realize now that not only is there no way to change the options, the options which were set in TB 78 do not work in TB 91 either.

Bill

**Comment by werano** [comment]
No way to get it work in TP 91.1

**Comment by caligraf** [comment]
I have fixed the compatibility issue with TB 91 in version 1.5.3. The options are available in Add-Ons manager tab, there is a new "wrench" button.
![image](https://user-images.githubusercontent.com/44136069/133326365-b999242a-dad3-4534-9893-4fd6536eead3.png)
The version 1.5.3 is not yet officially available, but you can download it here : https://github.com/caligraf/ChangeQuote/releases/download/1.5.3/ChangeQuote.xpi and install it manually.

**Comment by BillH99999** [comment]
@caligraf 

Thanks for adding support for TB 91.  I only use a few features of the extension, but so far all is looking good.

Thanks!
Bill
