### ISSUE TITLE
[Feature request] Ability to use long date

### ISSUE THREAD

**Issue by baheinrich** [caligraf/ChangeQuote#31]
I’m using changeQuote 1.5.3 with Thunderbird 91.4.1 under Windows 10.

I am currently able to make use of medium dates in replying; e.g., ‘On Mon., 3 Jan. 2022, at 21:24 (UTC-700), <name> wrote:’

My understanding is that Thunderbird pulls the date from the system settings. My short date is set to yyyy-mm-dd, while my long date is set to DDDD, d MMMM yyyy.

Is it possible for changeQuote (or some other about:config pref with which I’m unfamiliar) to use the system long date? Or is this a shortcoming of Thunderbird, that it can only use either short dates or medium dates?

**Comment by caligraf** [comment]
I just released a new version which add the possibility to use %LM and %LD in a customized date:
%LD : long date of week , example: Friday
%LM: month name, example : October
https://github.com/caligraf/ChangeQuote/releases/download/1.7.8/ChangeQuote.xpi

**Comment by baheinrich** [comment]
Thank you! I appreciate having this functionality available.
