### ISSUE TITLE
TB 102 compatibility

### ISSUE THREAD

**Issue by BillH99999** [caligraf/ChangeQuote#32]
changeQuote is flagged as not compatible with TB 102 which is coming out soon.  Are there plans to come out with a TB 102 compatible version?

Thanks,
Bill

**Comment by caligraf** [comment]
Merge done

**Comment by BillH99999** [comment]
What version will this be?

Thanks,
Bill

**Comment by caligraf** [comment]
Version 1.6
________________________________
De : BillH99999 ***@***.***>
Envoyé : mercredi 14 septembre 2022 06:08
À : caligraf/ChangeQuote ***@***.***>
Cc : caligraf ***@***.***>; Assign ***@***.***>
Objet : Re: [caligraf/ChangeQuote] TB 102 compatibility (Issue #32)


What version will this be?

Thanks,
Bill

**Comment by the-solipsist** [comment]
This issue can be closed.
