### ISSUE TITLE
Week and month 3 letters notation includes a trailing space?

### ISSUE THREAD

**Issue by SaltfishAmi** [caligraf/ChangeQuote#42]
Version 1.7.10, TB version 115

Date settings: `%D, %Y-%M-%d %H:%i %z`

Expected to see: `Wed, 2023-Dec-06 14:12 -0500`

Actually saw: `Wed , 2023-Dec -06 14:12 -0500`

**Comment by caligraf** [comment]
I did a fix, can you test the version 1.7.11:
https://github.com/caligraf/ChangeQuote/releases/download/1.7.11/ChangeQuote.xpi

**Comment by SaltfishAmi** [comment]
Resolved. Thanks!
