### ISSUE TITLE
Document what this does and how it works

### ISSUE THREAD

**Issue by bernd-wechner** [caligraf/ChangeQuote#5]
Alas there is no README.md, and nothing in the wiki. I installed it and can't see how it's done anything. Don't know where to look. I see this:

https://addons.thunderbird.net/en-US/thunderbird/addon/changequote/?src=cb-dl-popular

and there's at least a screen shot of its settings. But where do they hide?

**Comment by caligraf** [comment]
You can access settings screen by choosing changeQuote in the Add-on Preferences in the tool menu addins option
![addonMenu](https://user-images.githubusercontent.com/44136069/71646897-433aff80-2cee-11ea-9763-0ed98a7085d5.png)

**Comment by caligraf** [comment]
I updated the wiki : [https://github.com/caligraf/ChangeQuote/wiki](https://github.com/caligraf/ChangeQuote/wiki)

**Comment by openemitter** [comment]
closeIssue #5

**Comment by georg-d** [comment]
IMHO the issue can be closed :)
