### ISSUE TITLE
Compatibility with other AddOns

### ISSUE THREAD

**Issue by Pilkja** [caligraf/ChangeQuote#6]
I have incompatibilities with other AddOns (e.g. Identity Chooser, Tag Toolbar), they work incorrectly after installing ChangeQuote.
TB version 68.4.1 32bit
ChangeQuote version 1.2

**Comment by galantra** [comment]
What exactly is your issue? I also use Identity Chooser and haven't noticed anything.

**Comment by Pilkja** [comment]
The issue were probably **not due** to ChangeQuote. I'm closing this thread.
