### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by galantra** [caligraf/ChangeQuote#7]
I use Thunderbird in German. My reply headers look like this:

-------- Original Message --------
Subject: Re: what we were talking about
From: Harry <info@something.de>
To: Tom <me@anotherthing.de>
Date: Sun Jan 12 2020 17:42:57 GMT+0100 (Mitteleuropäische Normalzeit) 

My setting are:

![grafik](https://user-images.githubusercontent.com/52420923/72532157-2d434800-3873-11ea-8626-823a90a3917d.png)

What I would like to **_change_**: either remove _(Mitteleuropäische Normalzeit)_ or translate it into English.

**Comment by galantra** [comment]
Workaround: I changed the whole Thunderbird to English.

**Comment by caligraf** [comment]
Sorry for the delay, you can put "%D %M %d %Y %H:%i:%s GMT %z" in Angepasstes Format field to remove (Mitteleuropäische Normalzeit)

**Comment by galantra** [comment]
Thank you! :)

For some reason, it didn't change the reply header right away. Only after I selected "Reply in HTML" from the drop-down menu once.

![](https://github.com/caligraf/ChangeQuote/raw/master/Wiki/replydropdownmenu.png)

I don't have to do this every time. Now it works as intended via the simple _Reply_ button.
